version: "3.9"

services:
    reverseproxy:
        #image: reverseproxy
        build: ./reverseproxy/
        ports:
            - 8080:8080
        restart: always
 
    api:
        depends_on:
            - reverseproxy
        #image: api
        build: ./api/
        expose:
          - "80"
        restart: always